import Head from 'next/head'
import { Button, Typography } from '@mui/material'
import { ThemeModeContext } from 'src/providers/ThemeModeProvider'
import { useContext } from 'react'

export default function Home() {
  const { mode, setMode } = useContext(ThemeModeContext)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button onClick={() => setMode(mode === 'light' ? 'dark' : 'light')}>Change Mode</Button>
        <Typography variant='h1'>Hello World</Typography>
      </main>
    </>
  )
}
